### ISSUE TITLE
uploading fail

### ISSUE THREAD

**Issue by papaz0rgl** [jonderwaater/strava-smooth#1]
Hello, 

First thanks for the really useful app !!  Unfortunately the uploading is not working. 
Am I missing something ? 

See trace below : 

retrieving activity 989174748
No handlers could be found for logger "stravalib.model.Activity"
Processing activity "Course du midi" (989174748) from date 2017-05-16 10:05:14
File created: 989174748.gpx
File created: 989174748_smooth.gpx
File created: 989174748.png
Uploading activity...
Activity is duplicate
Deleting activity 989174748
Traceback (most recent call last):
  File "/usr/local/bin/smoothen", line 33, in <module>
    newactivity = upload.main(upl)
  File "/Library/Python/2.7/site-packages/smoothify/upload.py", line 57, in main
    newactivity = upload(client, gpxfile, title, desc, activity_type, private, overwrite, ori_id)
  File "/Library/Python/2.7/site-packages/smoothify/upload.py", line 81, in upload
    activity = upload(client, gpxfile, title, desc, activity_type, private, overwrite, duplicate_id=activity.id)
  File "/Library/Python/2.7/site-packages/smoothify/upload.py", line 69, in upload
    client.delete_activity(duplicate_id)
  File "/Library/Python/2.7/site-packages/stravalib/client.py", line 684, in delete_activity
    self.protocol.delete('/activities/{id}', id=activity_id)
  File "/Library/Python/2.7/site-packages/stravalib/protocol.py", line 273, in delete
    return self._request(url, params=params, method='DELETE', check_for_errors=check_for_errors, use_webhook_server=use_webhook_server)
  File "/Library/Python/2.7/site-packages/stravalib/protocol.py", line 170, in _request
    self._handle_protocol_error(raw)
  File "/Library/Python/2.7/site-packages/stravalib/protocol.py", line 215, in _handle_protocol_error
    raise x
requests.exceptions.HTTPError: 401 Client Error: Unauthorized [Authorization Error: [{u'field': u'delete', u'code': u'forbidden', u'resource': u'Application'}]]

**Comment by jonderwaater** [comment]
Hi papaz0rgl,

I presume you are running the python program on your device?
The situation is that Strava no longer allows external apps to delete user activities, and this broke the upload process because duplicates are not allowed. So you'd have to delete the activity by hand via the browser and then you can upload the gpx file that the program created, probably it's easiest to do that also via the browser. I had some communication with the Strava team about this problem but I don't foresee a convenient fix for this issue.

Best,
Jaap

ps. please note that the gpx file only contains location data, so no heart rate etc.

**Comment by papaz0rgl** [comment]
I'm trying to upload from my mac. And you're right what I have to do is
first delete the original move and then upload the smoothed one. I usually
do that directly on the web site.
The experience is bureaucratic and what make it worse is that the move that
I have to smoothen are the one recorded by the iPhone strava app itself.

When I record moves with my stunt watch I never need it.

Anyway thanks again for your app.

laurent


Le jeu. 18 mai 2017 à 15:07, jonderwaater <notifications@github.com> a
écrit :
